# Generated by Django 6.1 on 2026-08-27 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('IDEE', 'Idée'), ('PROTOTYPE', 'Prototype'), ('MVP', 'MVP'), ('CROISSANCE', 'Croissance')], max_length=20)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('technologies', models.CharField(max_length=255)),
                ('domaines_d_etude', models.CharField(max_length=255)),
                ('type_collaboration', models.CharField(choices=[('INVESTISSEMENT', 'Investissement'), ('PARTENARIAT_STRATEGIQUE', 'Partenariat stratégique'), ('ACQUISITION_SOLUTION', 'Acquisition de solution'), ('LICENCE_UTILISATION', "Licence d'utilisation"), ('INCUBATION', 'Incubation')], max_length=50)),
                ('resultat', models.TextField(blank=True, null=True)),
                ('porteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='Authentification.porteurprojet')),
            ],
        ),
    ]
