# Generated by Django 6.1 on 2026-08-10 21:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('statut_compte', models.CharField(default='ACTIF', max_length=20)),
                ('niveau_acces', models.CharField(default='ADMIN', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PorteurProjet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('statut_compte', models.CharField(default='ACTIF', max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(default='Cameroun', max_length=100)),
                ('telephone', models.CharField(max_length=30)),
                ('diplome', models.CharField(max_length=150)),
                ('annee_obtention', models.PositiveIntegerField()),
                ('etablissement', models.CharField(max_length=200)),
                ('langues', models.CharField(max_length=255)),
                ('github', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('statut_compte', models.CharField(default='ACTIF', max_length=20)),
                ('nom_startup', models.CharField(max_length=150)),
                ('secteur', models.CharField(max_length=150)),
                ('annee_creation', models.PositiveIntegerField()),
                ('numero_nu', models.CharField(max_length=100, unique=True)),
                ('type_startup', models.CharField(max_length=100)),
                ('type_collaboration', models.CharField(choices=[('INVESTISSEMENT', 'Investissement'), ('PARTENARIAT_STRATEGIQUE', 'Partenariat stratégique'), ('ACQUISITION_SOLUTION', 'Acquisition de solution'), ('LICENCE_UTILISATION', "Licence d'utilisation"), ('INCUBATION', 'Incubation')], max_length=40)),
                ('statut_validation', models.CharField(default='EN_ATTENTE', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StructureFinancement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('statut_compte', models.CharField(default='ACTIF', max_length=20)),
                ('nom_structure', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('pays', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('numero_nu', models.CharField(max_length=100, unique=True)),
                ('type_structure', models.CharField(choices=[('INCUBATEUR', 'Incubateur'), ('BANQUE', 'Banque'), ('FONDS_INVESTISSEMENT', "Fonds d'investissement"), ('ACCELERATEUR', 'Accélérateur'), ('ONG', 'ONG'), ('INSTITUTION_PUBLIQUE', 'Institution publique'), ('AUTRE', 'Autre')], max_length=50)),
                ('type_collaboration', models.CharField(choices=[('INVESTISSEMENT', 'Investissement'), ('PARTENARIAT_STRATEGIQUE', 'Partenariat stratégique'), ('ACQUISITION_SOLUTION', 'Acquisition de solution'), ('LICENCE_UTILISATION', "Licence d'utilisation"), ('INCUBATION', 'Incubation')], max_length=40)),
                ('statut_validation', models.CharField(default='EN_ATTENTE', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
